defaults:
  - _self_
  - augmentations: symmetric.yaml
  - wandb: private.yaml
  - data: medmnist.yaml
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

# disable hydra outputs
hydra:
  output_subdir: null
  run:
    dir: .

name: "deepclusterv2-imagenet100"
method: "deepclusterv2"
backbone:
  name: "vit_tiny"
  kwargs:
    pretrained: False
    img_size: 64
method_kwargs:
  proj_hidden_dim: 2048
  proj_output_dim: 128
  num_prototypes: [3000, 3000, 3000]
optimizer:
  name: "adamw"
  batch_size: 256
  lr: 3.0e-4
  classifier_lr: 3.0e-4
  weight_decay: 0.05
  kwargs:
    betas: [0.9, 0.95]
scheduler:
  name: "warmup_cosine"
checkpoint:
  enabled: True
  dir: "trained_models"
  frequency: 100
  monitor: 'val_acc1'
  mode: 'max'
auto_resume:
  enabled: False

# overwrite PL stuff
max_epochs: 400
devices: [0,]
sync_batchnorm: True
accelerator: "gpu"
strategy: "ddp"
precision: "32"
seed: 42

