defaults:
  - _self_
  - augmentations: asymmetric.yaml
  - wandb: private.yaml
  - data: pathmnist.yaml
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

# disable hydra outputs
hydra:
  output_subdir: null
  run:
    dir: .

name: "dino-medmnist-vit"
method: "dino"
backbone:
  name: "vit_tiny"
  kwargs:
    pretrained: False
method_kwargs:
  proj_hidden_dim: 512
  proj_output_dim: 128
  num_prototypes: 65536
  norm_last_layer: False
momentum:
  base_tau: 0.9995
  final_tau: 1.0
optimizer:
  name: "adamw"
  batch_size: 128
  lr: 0.005
  classifier_lr: 3e-3
  weight_decay: 1e-4
scheduler:
  name: "warmup_cosine"
  warmup_start_lr: 0.00001
checkpoint:
  enabled: True
  dir: "trained_models"
  frequency: 1
  monitor: 'val_acc1'
  mode: 'max'
auto_resume:
  enabled: False

max_epochs: 400
devices: [0,]
sync_batchnorm: True
accelerator: "gpu"
strategy: "ddp"
precision: "32"
seed: 42
