defaults:
  - _self_
  - augmentations: ressl.yaml
  - wandb: private.yaml
  - data: medmnist.yaml
  - grid_search: linear.yaml
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

# disable hydra outputs
hydra:
  output_subdir: null
  run:
    dir: .

name: "ressl-imagenet100"
method: "ressl"
backbone:
  name: "vit_tiny"
  kwargs:
    pretrained: False
    img_size: 64
method_kwargs:
  proj_output_dim: 256
  proj_hidden_dim: 4096
  base_tau_momentum: 0.99
  final_tau_momentum: 1.0
  momentum_classifier:
  temperature_q: 0.1
  temperature_k: 0.04
momentum:
  base_tau: 0.99
  final_tau: 1.0
optimizer:
  name: "adamw"
  batch_size: 256
  lr: 3.0e-4
  classifier_lr: 3.0e-4
  weight_decay: 0.05
  kwargs:
    betas: [0.9, 0.95]
scheduler:
  name: "warmup_cosine"
checkpoint:
  enabled: True
  dir: "trained_models"
  frequency: 100
  monitor: 'val_acc1'
  mode: 'max'
auto_resume:
  enabled: False
load:  # for self-supervised imagenet weight initialization
  enabled: False
  path: None


max_epochs: 400
devices: [0,]
sync_batchnorm: True
accelerator: "gpu"
strategy: "ddp"
precision: "32"
seed: 42