defaults:
  - _self_
  - augmentations: asymmetric.yaml
  - wandb: private.yaml
  - data: pathmnist.yaml
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

# disable hydra outputs
hydra:
  output_subdir: null
  run:
    dir: .

name: "simclr-medmnist-resnet"
method: "simclr"
backbone:
  name: "resnet50"
  kwargs:
    pretrained: False
method_kwargs:
  proj_hidden_dim: 512
  proj_output_dim: 128
  temperature: 0.07
optimizer:
  name: "lars"
  batch_size: 128
  lr: 0.3
  classifier_lr: 0.1
  weight_decay: 1e-4
  kwargs:
    clip_lr: True
    eta: 0.02
    exclude_bias_n_norm: True
scheduler:
  name: "warmup_cosine"
checkpoint:
  enabled: True
  dir: "trained_models"
  frequency: 1
  monitor: 'val_acc1'
  mode: 'max'
auto_resume:
  enabled: True

max_epochs: 400
devices: [0,]
sync_batchnorm: True
accelerator: "gpu"
strategy: "ddp"
precision: "32"
seed: 42
