defaults:
  - _self_
  - augmentations: symmetric_weak.yaml
  - wandb: private.yaml
  - data: medmnist.yaml
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

# disable hydra outputs
hydra:
  output_subdir: null
  run:
    dir: .

name: "simsiam-medmnist-resnet"
method: "simsiam"
backbone:
  name: "resnet50"
  kwargs:
    pretrained: False
method_kwargs:
  proj_hidden_dim: 2048
  proj_output_dim: 2048
  pred_hidden_dim: 512
  temperature: 0.2
optimizer:
  name: "adamw"
  batch_size: 256
  lr: 3.0e-4
  classifier_lr: 3.0e-4
  weight_decay: 0.05
  kwargs:
    betas: [0.9, 0.95]
scheduler:
  name: "warmup_cosine"
checkpoint:
  enabled: True
  dir: "trained_models"
  frequency: 100
  monitor: 'val_acc1'
  mode: 'max'
auto_resume:
  enabled: False
max_epochs: 400
devices: [0,]
sync_batchnorm: True
accelerator: "gpu"
strategy: "ddp"
precision: "32"
seed: 42
