defaults:
  - _self_
  - wandb: private.yaml
  - data: pathmnist.yaml
  - grid_search: linear.yaml
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

# disable hydra outputs
hydra:
  output_subdir: null
  run:
    dir: .

# When finetune: True and pretrained_feature_extractor: None, it corresponds to supervised learning
name: "supervised"
pretrained_feature_extractor: None
method: "base"
backbone:
  name: "resnet50"
  kwargs:
    pretrained: False
pretrain_method: "simsiam"
optimizer:
  name: "adamw"
  batch_size: 256
  lr: 3.0e-4
  classifier_lr: 3.0e-4
  weight_decay: 0.05
  kwargs:
    betas: [0.9, 0.95]
scheduler:
  name: "warmup_cosine"
checkpoint:
  enabled: True
  dir: "trained_models"
  frequency: 100
  monitor: 'val_acc'
auto_resume:
  enabled: False
downstream_classifier:
  name: "linear"
  kwargs:
    hidden_dim: 1024
    num_seeds: 5
to_csv:
  enabled: True
  name: "downstream_results.csv"
  
# overwrite PL stuff
max_epochs: 100
devices: [0]
sync_batchnorm: True
accelerator: "gpu"
strategy: "ddp"
precision: 32
finetune: True
