seed: 42
Device:
  gpu: True
  gpu_id: 0
  num_workers: -1  # Infer from available CPUs
Dataset:
  path: "datasets/"
  name: "medmnist"
  params:
    medmnist_flag: PATH
    image_size: 64
Pretrain:
  ssl_method: "simclr"
  params:
    hidden_dim: 512
    pretrained: True
    output_dim: 128
    encoder: "resnet50"
    max_epochs: 200
    batch_size: 256
    learning_rate: 3e-4
    weight_decay: 1e-4
    temperature: 0.07
    n_views: 2
    feature_dim: 128
Downstream:
  eval_method: "linear"
  params:
    hidden_dim: 512
    encoder: "resnet50"
    max_epochs: 200
    batch_size: 256
    learning_rate: 3e-4
    weight_decay: 1e-4
    pretrained_path: ???  # Mandatory field
Logging:
  tool: "wandb"
  log_steps: 100
