seed: 42
Device:
  gpu: True
  gpu_id: 0
  num_workers: -1  # Infer from available CPUs
  fp16: False
Dataset:
  path: "datasets/"
  name: MEDMNIST
  params:
    medmnist_flag: PATH
    image_size: 64
Training:
  params:
    batch_size: 256
    max_epochs: 200
    learning_rate: 3e-4
    weight_decay: 1e-4
  Pretrain:
    ssl_method: SIMCLR
    params:
      encoder: "resnet50"
      pretrained: True
      hidden_dim: 512
      feature_dim: 128
      output_dim: 128
      temperature: 0.07
      n_views: 2
  Downstream:
    eval_method: LINEAR
    params:
      hidden_dim: 512
      encoder: "resnet50"
      pretrained_path: ???  # Mandatory field
Logging:
  tool: WANDB
  log_steps: 100
