defaults:
  - _self_
  - wandb: private.yaml
  - data: pathmnist.yaml
  - ood_data: pathmnist.yaml
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

# disable hydra outputs
hydra:
  output_subdir: null
  run:
    dir: .

name: "byol-medmnist-linear"
pretrained_feature_extractor: None      
backbone:
  name: "resnet50"
  kwargs:
    img_size: 64
    pretrained: False
pretrain_method: "byol"
optimizer:
  name: "sgd"
  batch_size: 256
  lr: [0.1, 0.01, 0.001]
  weight_decay: [0, 0.1, 0.01]
scheduler:
  name: "step"
  lr_decay_steps: [60, 80]
checkpoint:
  enabled: True
  dir: "trained_models"
  frequency: 100
  monitor: 'val_acc'
auto_resume:
  enabled: False
downstream_classifier:
  name: "linear"
  kwargs:
    hidden_dim: 1024
    num_seeds: 5
to_csv:
  enabled: True
  name: "downstream_results.csv"

# overwrite PL stuff
max_epochs: 100
devices: [0]
sync_batchnorm: True
accelerator: "gpu"
strategy: "ddp"
precision: 32
finetune: False